### ISSUE TITLE
Error on Chromecast discovery

### ISSUE THREAD

**Issue by iamthesq** [firstone/RESTRemote#4]
Throwing an error when trying to discover Chromecast devices

`Current Version: 0.9.1`

```2022-06-05 08:59:44,768 Controller polyinterface      DEBUG    remotecontroller:discover: Starting device discovery
2022-06-05 08:59:44,769 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for android
2022-06-05 08:59:44,769 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for web_os
2022-06-05 08:59:44,769 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for tivo_ip
2022-06-05 08:59:44,769 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for denon_avr
2022-06-05 08:59:44,770 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for onkyo_avr
2022-06-05 08:59:44,770 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for esp8266
2022-06-05 08:59:44,770 Controller polyinterface      DEBUG    remotecontroller:discover: Running discovery for chromecast
2022-06-05 08:59:49,838 Controller polyinterface      ERROR    polyinterface:_parseInput: _parseInput: failed controller.runCmd(DISCOVER) 'Chromecast' object has no attribute 'device'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/polyinterface/polyinterface.py", line 842, in _parseInput
    self.nodes[input[key]['address']].runCmd(input[key])
  File "/home/pi/.local/lib/python3.9/site-packages/polyinterface/polyinterface.py", line 745, in runCmd
    fun(self, command)
  File "/home/pi/.polyglot/nodeservers/AVRemote/poly/remotecontroller.py", line 188, in discover
    devices = self.get_device_driver(driverName,
  File "/home/pi/.polyglot/nodeservers/AVRemote/drivers/chromecast.py", line 143, in discoverDevices
    friendly_name = cast.device.friendly_name
AttributeError: 'Chromecast' object has no attribute 'device'```

**Comment by firstone** [comment]
What version is your pychromecast library?

**Comment by iamthesq** [comment]
12.1.3

**Comment by firstone** [comment]
Fixed in the latest version
